const shoes = [
  {
    id: 1,
    name: "Nike Air Max Ishod",
    image: "/Images/air-max-ishod-mens-shoes-DwRtpQ.png",
    category: "Men's Shoes",
    price: 110,
    amount: 1,
  },
  {
    id: 2,
    name: "Nike Air Max 1",
    image: "/Images/air-max-1-mens-shoes-2C5sX2.png",
    category: "Men's Shoes",
    price: 140,
    amount: 1,
  },
  {
    id: 3,
    name: "Nike Air Force 1 '07 LV8",
    image: "/Images/air-force-1-07-lv8-mens-shoes-Zj9bVF.jpg",
    category: "Men's Shoes",
    price: 125,
    amount: 1,
  },
  {
    id: 4,
    name: "Nike Air Max 90 GORE-TEX",
    image: "/Images/air-max-90-gore-tex-mens-shoes-cZwz8t.png",
    category: "Men's Shoes",
    price: 160,
    amount: 1,
  },
  {
    id: 5,
    name: "Nike Air VaporMax Plus",
    image: "/Images/air-vapormax-plus-chicago-mens-shoes-nC0dzF.png",
    category: "Men's Shoes",
    price: 210,
    amount: 1,
  },
  {
    id: 6,
    name: "Nike Air Max 90",
    image: "/Images/air-max-90-mens-shoes-Bd2qnn.png",
    category: "Men's Shoes",
    price: 130,
    amount: 1,
  },
  {
    id: 7,
    name: "Nike G.T. Jump 2 ASW",
    image: "/Images/gt-jump-2-asw-basketball-shoes-Xjh0vC.jpg",
    category: "Basketball Shoes",
    price: 190,
    amount: 1,
  },
  {
    id: 8,
    name: "Nike Air Max 95 Premium",
    image: "/Images/air-max-95-premium-mens-shoe-4Nzc1w.png",
    category: "Men's Shoes",
    price: 170,
    amount: 1,
  },
  {
    id: 9,
    name: "LeBron NXXT Gen AMPD IPS",
    image: "/Images/lebron-nxxt-gen-ampd-ips-basketball-shoes-CH9Kwr.png",
    category: "Basketball Shoes",
    price: 170,
    amount: 1,
  },
  {
    id: 10,
    name: "Nike Phantom GX 2 Elite LV8",
    image: "/Images/phantom-gx-2-elite-lv8-fg-low-top-soccer-cleats-zwTxf2.png",
    category: "FG Low-Top Soccer Cleats",
    price: 270,
    amount: 1,
  },
  {
    id: 11,
    name: "Nike Free Metcon 5",
    image: "/Images/free-metcon-5-mens-workout-shoes-H0Qszz.png",
    category: "Men's Workout Shoes",
    price: 120,
    amount: 1,
  },
  {
    id: 12,
    name: "Nike Phantom GX Elite",
    image:
      "/Images/phantom-gx-elite-firm-ground-low-top-soccer-cleat-WGRzk4.png",
    category: "FG Low-Top Soccer Cleat",
    price: 260,
    amount: 1,
  },
];

export default shoes;
